apiVersion: v1
kind: Service
metadata:
  name: barkuni-corp-service
spec:
  selector:
    app: barkuni-corp
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 8000
  type: {{ .Values.service.type }}
